
CREATE TABLE [PRODUTOS]
([CÓDIGO] VARCHAR(10) NOT NULL, --chave primaria nao pode aceitar nulos
[DESCRITOR] VARCHAR(100) NULL,
[SABOR] VARCHAR(50) NULL,
[TAMANHO] VARCHAR(50) NULL,
[EMBALAGEM] VARCHAR(50) NULL,
[PREÇO LISTA] FLOAT NULL,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CÓDIGO]))

CREATE TABLE [VENDEDORES]
([MATRÍCULA] VARCHAR(5) NOT NULL,
[NOME] VARCHAR(100) NULL,
[BAIRRO] VARCHAR(50) NULL,
[COMISSÃO] FLOAT NULL,
[DATA ADMISSÃO] DATE NULL,
[FÉRIAS] BIT NULL,
CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([MATRÍCULA]))

CREATE TABLE [CLIENTES]
([CPF] VARCHAR(11) NOT NULL,
[NOME] VARCHAR(100) NULL,
[ENDEREÇO] VARCHAR(150) NULL,
[BAIRRO] VARCHAR(50) NULL,
[CIDADE] VARCHAR(50) NULL,
[ESTADO] VARCHAR(50) NULL,
[CEP] VARCHAR(8) NULL,
[IDADE] INT NULL,
[SEXO] VARCHAR(1) NULL,
[LIMITE CREDITO] FLOAT NULL,
[VOLUME COMPRA] FLOAT NULL,
[DATA DE NASCIMENTO] DATE NULL,
[PRIMEIRA COMPRA] BIT NULL,
CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED ([CPF]))

--CRIANDO CHAVE ESTRANGEIRA NA TABELA NOTAS
ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTES]
FOREIGN KEY(CPF) REFERENCES [CLIENTES] ([CPF])