
SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002334'

SELECT * FROM [PRODUTOS] WHERE [CÓDIGO] = '1002334'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CÓDIGO], A.[PREÇO LISTA]
FROM [PRODUTOS] A INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
WHERE [CÓDIGO] = '1002334'

UPDATE [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 8
WHERE [CODIGO DO PRODUTO] = '1002334'

-- O MERGE ATUALIZA OS DADOS DE UMA TABELA COM OS DADOS DE OUTRA TABELA
MERGE INTO [PRODUTOS] A
USING [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
AND A.[CÓDIGO] = '1002334'
WHEN MATCHED THEN
UPDATE SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA];

--Repetindo o enunciado: Podemos observar que os vendedores possuem bairros associados a eles. 
--Vamos aumentar em 30% o volume de compra dos clientes que possuem, em seus endereços, bairros onde os vendedores possuam escritórios.
MERGE INTO [dbo].[CLIENTES] A
USING  [dbo].[VENDEDORES] B
ON A.[BAIRRO] = B.[BAIRRO] 
WHEN MATCHED THEN
UPDATE SET A.[VOLUME COMPRA] = A.[VOLUME COMPRA]*1.3;