--Consultando no BD
SELECT *  FROM [ITENS NOTAS FISCAIS] 
WHERE [QUANTIDADE] > 60 AND [PREÇO] <= 3

-- utilizando o LIKE para filtrar strings

--produtos que tem litros no nome do produto
SELECT *  FROM [dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%Litros%'

--produtos que tem litros no final do nome do produto
SELECT *  FROM [dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%Litros'

--produtos que tem litros no nome do produto e são do sabor laranja
SELECT *  FROM [dbo].[TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%Litros%' AND [SABOR]='Laranja'

-- Quantos clientes possuem o último sobrenome Mattos?
SELECT *  FROM [dbo].[TABELA DE CLIENTES]
WHERE [NOME] LIKE '%Mattos'

--DISTINCT - retorna somente linhas com valores diferentes
SELECT DISTINCT EMBALAGEM, TAMANHO FROM [dbo].[TABELA DE PRODUTOS]
SELECT DISTINCT [BAIRRO] FROM [dbo].[TABELA DE CLIENTES] WHERE [CIDADE]= 'Rio de Janeiro'

--TOP - Limita a saida para os primeiros X registros
SELECT TOP (5) * FROM [dbo].[TABELA DE CLIENTES]
SELECT TOP(10) * FROM [dbo].[NOTAS FISCAIS] WHERE [DATA] = '2017-01-01'

-- ORDER BY - Ordena a saida da consulta
--Ordena do mais barato pro mais caro
SELECT * FROM [dbo].[TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA]
--Ordena do mais caro pro mais barato
SELECT * FROM [dbo].[TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA] DESC7

-- GROUP BY - agrupa os valores
SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [dbo].[TABELA DE CLIENTES] GROUP BY ESTADO
SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [dbo].[TABELA DE CLIENTES] GROUP BY ESTADO
SELECT ESTADO, [LIMITE DE CREDITO] FROM [dbo].[TABELA DE CLIENTES]
SELECT [EMBALAGEM], MIN([PREÇO DE LISTA]) FROM [dbo].[TABELA DE PRODUTOS] GROUP BY EMBALAGEM
SELECT [EMBALAGEM], COUNT(*) FROM [dbo].[TABELA DE PRODUTOS] GROUP BY EMBALAGEM -- QUANTOS PRODUTOS POR EMBALAGEM
SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [dbo].[TABELA DE CLIENTES] WHERE [ESTADO] = 'SP' GROUP BY BAIRRO
SELECT BAIRRO,ESTADO, SUM([LIMITE DE CREDITO]) FROM [dbo].[TABELA DE CLIENTES] WHERE [ESTADO] = 'SP' GROUP BY BAIRRO, ESTADO

-- HAVING - faz um filtro no resultado do GROUP BY
SELECT BAIRRO,ESTADO, SUM([LIMITE DE CREDITO]) AS SOMA_LIMITE FROM [dbo].[TABELA DE CLIENTES]
WHERE [ESTADO] = 'SP'  GROUP BY BAIRRO, ESTADO HAVING SUM([LIMITE DE CREDITO])>=140000

SELECT [CPF], COUNT(*) FROM [dbo].[NOTAS FISCAIS] 
WHERE YEAR(DATA)=2016
GROUP BY CPF HAVING COUNT(*) > 2000
