
DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT, @LIMITE_BREAK INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 10
SET @LIMITE_BREAK = 2

WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
   PRINT @LIMITE_MINIMO
   SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
   IF @LIMITE_MINIMO = @LIMITE_BREAK
   BEGIN
      PRINT 'Saindo por causa do BREAK'
      BREAK
   END
END

---
DECLARE @DATAFINAL DATE, @DATAATUAL DATE, @CONTDIA INT, @CONTTOTAL INT
SET @DATAATUAL = '20170101'
SET @DATAFINAL = '20170110'
SET @CONTTOTAL = 0
WHILE @DATAATUAL<= @DATAFINAL
BEGIN 
	SELECT @CONTDIA = COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATAATUAL
	SET @CONTTOTAL = @CONTTOTAL + @CONTDIA
	SELECT @DATAATUAL = DATEADD(DAY, 1, @DATAATUAL)
	PRINT @CONTTOTAL
	PRINT @CONTDIA
END

